# Generated by Django 5.2 on 2025-04-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('url', models.URLField(max_length=2000)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
